# _config.yml
title: "Marcos Natanael Da Silva - CV"
description: "Analista de Sistemas | Desarrollador Full Stack"
remote_theme: pages-themes/cayman@v0.2.0

# Incluir CSS personalizado
include:
  - assets